site_name: BMEVIAUAC01 Data-driven systems
site_author: Dudás Ákos
copyright: Copyright &copy; BME AUT
repo_name: bmeviauac01/datadriven-en
repo_url: https://github.com/bmeviauac01/datadriven-en

theme:
  name: material
  custom_dir: theme-overrides
  language: en
  palette:
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs

extra_css:
  - extra-material-theme.css

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true

nav:
  - index.md
  - "Database":
      - db/index.md
      - db/mssql.md
      - db/mongodb.md
      - "Sample database: mssql.sql": https://raw.githubusercontent.com/bmeviauac01/adatvezerelt/master/docs/db/mssql.sql
      - "Sample database: mongo.js": https://raw.githubusercontent.com/bmeviauac01/adatvezerelt/master/docs/db/mongo.js
  - "Lecture notes":
      - lecture-notes/architecture/index.md
      - lecture-notes/transactions/index.md
      - lecture-notes/mssql/sql.md
      - lecture-notes/mssql/server-side-programming.md
      - lecture-notes/linq/index.md
      - lecture-notes/mongodb/index.md
      - lecture-notes/di/index.md
      - "REST and WebAPI sample app (GitHub)": https://github.com/bmeviauac01/rest-webapi-sample
      - "ASP.NET Core DI sample app (GitHub)": https://github.com/bmeviauac01/todoapi-di-sample
      - "Sample three-tier webapp (GitHub)": https://github.com/bmeviauac01/threelayered-aspnetcore-sample
  - "Seminars":
      - seminar/transactions/index.md
      - seminar/mssql/index.md
      - seminar/ef/index.md
      - seminar/mongodb/index.md
      - seminar/jpa/index.md
      - seminar/rest/index.md
  - "Homework":
      - homework/index.md
      - homework/mssql/index.md
      - homework/adonet/index.md
      - homework/ef/index.md
      - homework/mongodb/index.md
      - homework/rest/index.md
      - homework/GitHub.md
      - homework/GitHub-Actions.md
      - homework/VisualStudio.md
