name: Build Docker images for AHK

on:
  push:
    paths:
      - "ahk/**"
      - "megoldas/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build all images with compose
        run: |
          cd ahk/src
          docker-compose build
      - name: Test sample solution for TSQL
        run: docker run --rm -v $(pwd)/megoldas/tsql:/megoldas bmeviauac01/hf-tsql
      - name: Test sample solution for ADONET
        run: docker run --rm -v $(pwd)/megoldas/adonet:/megoldas bmeviauac01/hf-adonet
      - name: Test sample solution for EF
        run: docker run --rm -v $(pwd)/megoldas/ef:/megoldas bmeviauac01/hf-ef
      - name: Test sample solution for MongoDB
        run: docker run --rm -v $(pwd)/megoldas/mongo:/megoldas bmeviauac01/hf-mongo
      - name: Test sample solution for WebApi
        run: docker run --rm -v $(pwd)/megoldas/webapi:/megoldas bmeviauac01/hf-webapi
      - name: Tag and push docker images
        env:
          AHK_DOCKER_IMAGE_TAG: "2019"
          DOCKER_REG_USERNAME: ${{ secrets.DOCKER_REG_USERNAME }}
          DOCKER_REG_TOKEN: ${{ secrets.DOCKER_REG_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u $DOCKER_REG_USERNAME -p $DOCKER_REG_TOKEN
          docker tag bmeviauac01/hf-tsql docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-tsql:$AHK_DOCKER_IMAGE_TAG
          docker push docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-tsql:$AHK_DOCKER_IMAGE_TAG
          docker tag bmeviauac01/hf-adonet docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-adonet:$AHK_DOCKER_IMAGE_TAG
          docker push docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-adonet:$AHK_DOCKER_IMAGE_TAG
          docker tag bmeviauac01/hf-ef docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-ef:$AHK_DOCKER_IMAGE_TAG
          docker push docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-ef:$AHK_DOCKER_IMAGE_TAG
          docker tag bmeviauac01/hf-mongo docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-mongo:$AHK_DOCKER_IMAGE_TAG
          docker push docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-mongo:$AHK_DOCKER_IMAGE_TAG
          docker tag bmeviauac01/hf-webapi docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-webapi:$AHK_DOCKER_IMAGE_TAG
          docker push docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-webapi:$AHK_DOCKER_IMAGE_TAG
          docker logout docker.pkg.github.com
