name: Build Docker images for AHK

on:
  push:
    paths:
      - "ahk/**"
      - "megoldas/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build all images with compose
        run: |
          cd ahk/src
          docker-compose -f docker-compose.mssqldotnet.yml build
          docker-compose build
      - name: Test sample solution for TSQL
        run: docker run --rm -v $(pwd)/megoldas/tsql:/megoldas docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-tsql:2019
      - name: Test sample solution for ADONET
        run: docker run --rm -v $(pwd)/megoldas/adonet:/megoldas docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-adonet:2019
      - name: Test sample solution for EF
        run: docker run --rm -v $(pwd)/megoldas/ef:/megoldas docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-ef:2019
      - name: Test sample solution for MongoDB
        run: docker run --rm -v $(pwd)/megoldas/mongo:/megoldas docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-mongo:2019
      - name: Test sample solution for WebApi
        run: docker run --rm -v $(pwd)/megoldas/webapi:/megoldas docker.pkg.github.com/bmeviauac01/hazi-feladatok/hf-webapi:2019
      - name: Push Docker images
        run: |
          cd ahk/src
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker-compose push
          docker logout docker.pkg.github.com
